apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "service-name-emg-sidecar.labels" . | nindent 4 }}
  name: {{ include "service-name-emg-sidecar.fullname" . }}
data:
{{- if .Values.configmap }}{{ if .Values.configmap.data }}
{{ toYaml .Values.configmap.data | indent 2 }}
{{- end }}{{ end }}