apiVersion: v1
kind: Service
metadata:
  name: {{ include "service-name-emg-sidecar.fullname" . }}
  labels:
    {{- include "service-name-emg-sidecar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http-8000
      protocol: TCP
      name: http
  selector:
    {{- include "service-name-emg-sidecar.selectorLabels" . | nindent 4 }}
