replicaCount: 1
configmap:
  data:
    PRINT_TOKEN: "Y"
    SPRING_PROFILE: ah-sa-int
    OAUTH_SERVICE_HOST: https://int-uk-apis.svc.azuk-scc-int.ec1.aws.aztec.cloud.allianz/azuk/ds/uam/identity/oauthv2/v1/token
    DEV_APP_CLIENT_ID: Il3GcgUK9RUSz5xfQAratMq0rdiPPjZt
    INGRESS_URL: https://int-uk-apis.svc.azuk-scc-int.ec1.aws.aztec.cloud.allianz/azuk/ds/eventreceiver/v1/coreeventreceiver/eventsink/push

#Add a readiness gate with conditionType:
#target-health.alb.ingress.k8s.aws/<ingress name>_<service name>_<service port> to your pod.
#This is required if the target type in ALB ingress is ip
readinessGates:
  enabled: false
  conditions:
    - conditionType: target-health.alb.ingress.k8s.aws/ah-sa_ah-sa-lv-event-projector_8080

pod:
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 6
    targetCPUUtilizationPercentage: 200
    targetMemoryUtilizationPercentage: 150