replicaCount: 1

configmap:
  data:
    PRINT_TOKEN: "Y"
    SPRING_PROFILE: ah-sa-ci
    OAUTH_SERVICE_HOST: https://dev-uk-apis.svc.azuk-scc-ci.ec1.aws.aztec.cloud.allianz/azuk/ds/uam/identity/oauthv2/v1/token
    DEV_APP_CLIENT_ID: AAARagptpJkZJPL1q9v5Wx56hipmhGDm
    INGRESS_URL: https://dev-uk-apis.svc.azuk-scc-ci.ec1.aws.aztec.cloud.allianz/azuk/ds/eventreceiver/v1/coreeventreceiver/eventsink/push

appService:
  image:
    # Overrides the image tag whose default is the chart version.
    tag: 1.0.0
  resources:
    limits:
      cpu: 100m
      memory: 384Mi
    requests:
      cpu: 50m
      memory: 192Mi

sidecar:
  resources:
    limits:
      cpu: 50m
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 192Mi

  containerEnv:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:MaxRAMPercentage=85.0'
    - name: EDGEMICRO_CONFIG
      value: ZWRnZV9jb25maWc6CiAgYm9vdHN0cmFwOiA+LQogICAgaHR0cHM6Ly9kZXYtdWstYXBpcy5zdmMuYXp1ay1zY2MtY2kuZWMxLmF3cy5henRlYy5jbG91ZC5hbGxpYW56L2VkZ2VtaWNyby9ib290c3RyYXAvb3JnYW5pemF0aW9uL3VrL2Vudmlyb25tZW50L2RldgogIGp3dF9wdWJsaWNfa2V5OiAnaHR0cHM6Ly9kZXYtdWstYXBpcy5zdmMuYXp1ay1zY2MtY2kuZWMxLmF3cy5henRlYy5jbG91ZC5hbGxpYW56L2VkZ2VtaWNyby1hdXRoL3B1YmxpY0tleScKICBtYW5hZ2VtZW50VXJpOiAnaHR0cHM6Ly9wcmUtZWRnZS1hcGlzLnN2Yy5henVrLXNjYy1jaS5lYzEuYXdzLmF6dGVjLmNsb3VkLmFsbGlhbnonCiAgdmF1bHROYW1lOiBtaWNyb2dhdGV3YXkKICBhdXRoVXJpOiAnaHR0cHM6Ly9kZXYtdWstYXBpcy5zdmMuYXp1ay1zY2MtY2kuZWMxLmF3cy5henRlYy5jbG91ZC5hbGxpYW56L2VkZ2VtaWNyby1hdXRoJwogIGJhc2VVcmk6ICdodHRwczovL2Rldi11ay1hcGlzLnN2Yy5henVrLXNjYy1jaS5lYzEuYXdzLmF6dGVjLmNsb3VkLmFsbGlhbnovZWRnZW1pY3JvLyVzL29yZ2FuaXphdGlvbi8lcy9lbnZpcm9ubWVudC8lcycKICBib290c3RyYXBNZXNzYWdlOiBQbGVhc2UgY29weSB0aGUgZm9sbG93aW5nIHByb3BlcnR5IHRvIHRoZSBlZGdlIG1pY3JvIGFnZW50IGNvbmZpZwogIGtleVNlY3JldE1lc3NhZ2U6IFRoZSBmb2xsb3dpbmcgY3JlZGVudGlhbHMgYXJlIHJlcXVpcmVkIHRvIHN0YXJ0IGVkZ2UgbWljcm8KICBwcm9kdWN0czogJ2h0dHBzOi8vZGV2LXVrLWFwaXMuc3ZjLmF6dWstc2NjLWNpLmVjMS5hd3MuYXp0ZWMuY2xvdWQuYWxsaWFuei9lZGdlbWljcm8tYXV0aC9wcm9kdWN0cycKZWRnZW1pY3JvOgogIHBvcnQ6IDgwMDAKICBwcm94eToKICAgIHR1bm5lbDogZmFsc2UKICAgICN1cmw6ICdodHRwOi8vcHJveHkuYXp1ay1zY2MtY2kuZWMxLmF3cy5henRlYy5jbG91ZC5hbGxpYW56Ojg4ODgnCiAgICBlbmFibGVkOiBmYWxzZQogIG1heF9jb25uZWN0aW9uczogMTAwMAojICBjb25maWdfY2hhbmdlX3BvbGxfaW50ZXJ2YWw6IDM2MDAKICBkaXNhYmxlX2NvbmZpZ19wb2xsX2ludGVydmFsOiB0cnVlCiAgbG9nZ2luZzoKICAgIGxldmVsOiBpbmZvCiAgICBkaXI6IC92YXIvdG1wCiAgICBzdGF0c19sb2dfaW50ZXJ2YWw6IDYwCiAgICByb3RhdGVfaW50ZXJ2YWw6IDI0CiAgcGx1Z2luczoKICAgIHNlcXVlbmNlOgogICAgICAtIGhlYWx0aGNoZWNrCiAgICAgIC0gc2VydmljZWNoZWNrCiAgICAgIC0gb2F1dGgKICAgICAgLSBzY29wZXNjaGVjawpoZWFkZXJzOgogIHgtZm9yd2FyZGVkLWZvcjogdHJ1ZQogIHgtZm9yd2FyZGVkLWhvc3Q6IHRydWUKICB4LXJlcXVlc3QtaWQ6IHRydWUKICB4LXJlc3BvbnNlLXRpbWU6IHRydWUKICB2aWE6IHRydWUKaGVhbHRoY2hlY2s6CiAgaGVhbHRoY2hlY2tfdXJsOiAvaGVhbHRoCnNlcnZpY2VjaGVjazoKICBzZXJ2aWNlY2hlY2tfdXJsOiAvX19oZWFsdGgKICBzZXJ2aWNlY2hlY2tfcG9ydDogODA4MApvYXV0aDoKICBhbGxvd05vQXV0aG9yaXphdGlvbjogZmFsc2UKICBhbGxvd0ludmFsaWRBdXRob3JpemF0aW9uOiBmYWxzZQogIGFsbG93T0F1dGhPbmx5OiB0cnVlCiAgYWxsb3dBUElLZXlPbmx5OiBmYWxzZQogIGtlZXAtYXV0aG9yaXphdGlvbi1oZWFkZXI6IHRydWUKICBncmFjZVBlcmlvZDogMTAKICB2ZXJpZnlfYXBpX2tleV91cmw6ICdodHRwczovL2Rldi11ay1hcGlzLnN2Yy5henVrLXNjYy1jaS5lYzEuYXdzLmF6dGVjLmNsb3VkLmFsbGlhbnovZWRnZW1pY3JvLWF1dGgvdmVyaWZ5QXBpS2V5JwogIGNhY2hlS2V5OiB0cnVlCnNjb3Blc2NoZWNrOgogIHNjb3Blc2NoZWNrX2xpc3Q6ICJQT1NUPXVybjphenVrOnBlcnNvbmFsOmFuaW1hbGhlYWx0aDpzYTpsdjpjbG91ZDpldmVudC1wcm9qZWN0b3IiCgphbmFseXRpY3M6CiAgdXJpOiA+LQogICAgaHR0cHM6Ly9kZXYtdWstYXBpcy5zdmMuYXp1ay1zY2MtY2kuZWMxLmF3cy5henRlYy5jbG91ZC5hbGxpYW56L2VkZ2VtaWNyby9heHB1Ymxpc2hlci9vcmdhbml6YXRpb24vdWsvZW52aXJvbm1lbnQvZGV2CiAgYnVmZmVyU2l6ZTogMTAwMDAKICBiYXRjaFNpemU6IDIwMDAKICBmbHVzaEludGVydmFsOiAzNjAwMDAwCiAgcmVsYXRpdmVQYXRoOiAvX19oZWFsdGg=
    - name: EDGEMICRO_ORG
      value: uk
    - name: EDGEMICRO_ENV
      value: dev
    - name: EDGEMICRO_KEY
      valueFrom:
        secretKeyRef:
          name: apigee-secret
          key: EDGEMICRO_KEY
    - name: EDGEMICRO_SECRET
      valueFrom:
        secretKeyRef:
          name: apigee-secret
          key: EDGEMICRO_SECRET
    - name: EDGEMICRO_PROCESSES
      value: "2"
    - name: SERVICE_NAME
      value: ah-sa-lv-event-projector
    - name: PROXY_NAME
      value: edgemicro_ah-sa-lv-event-projector
    - name: CONTAINER_PORT
      value: "8080"
    - name: EDGEMICRO_BASE_PATH
      value: /
    - name: EDGEMICRO_LOCAL_PROXY
      value: "1"
    - name: NODE_EXTRA_CA_CERTS
      value: /opt/apigee/certs/ca-certificates.crt
    - name: EDGEMICRO_PLUGIN_DIR
      value: /usr/local/lib/node_modules/edgemicro/plugins/


#Add a readiness gate with conditionType:
#target-health.alb.ingress.k8s.aws/<ingress name>_<service name>_<service port> to your pod.
#This is required if the target type in ALB ingress is ip
readinessGates:
  enabled: true
  conditions:
    - conditionType: target-health.alb.ingress.k8s.aws/ah-sa_azukp-ah-sa-lv-event-projector-emg_8000
    - conditionType: target-health.alb.ingress.k8s.aws/ah-sa-ext_azukp-ah-sa-lv-event-projector-emg_8000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80