replicaCount: 1

configmap:
  data:
    PRINT_TOKEN: "Y"
    SPRING_PROFILE: ah-sa-prod
    OAUTH_SERVICE_HOST: https://pro-uk-apis.svc.azuk-scc-prod.ew3.aws.aztec.cloud.allianz/azuk/ds/uam/identity/oauthv2/v1/token
    DEV_APP_CLIENT_ID: 1yBIjGPouH2XfoBHOZ9oGRM5xh8Qo4LU
    INGRESS_URL: https://pro-uk-apis.svc.azuk-scc-prod.ew3.aws.aztec.cloud.allianz/azuk/ds/eventreceiver/v1/coreeventreceiver/eventsink/push

appService:
  resources:
    limits:
      cpu: 400m
      memory: 768Mi
    requests:
      cpu: 200m
      memory: 384Mi

  image:
    # Overrides the image tag whose default is the chart version.
    tag: 1.0.0

sidecar:
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  containerEnv:
    - name: EDGEMICRO_CONFIG
      value: ZWRnZV9jb25maWc6CiAgYm9vdHN0cmFwOiA+LQogICAgaHR0cHM6Ly9wcm8tdWstYXBpcy5zdmMuYXp1ay1zY2MtcHJvZC5ldzMuYXdzLmF6dGVjLmNsb3VkLmFsbGlhbnovZWRnZW1pY3JvL2Jvb3RzdHJhcC9vcmdhbml6YXRpb24vdWsvZW52aXJvbm1lbnQvaW50ZXJuYWwKICBqd3RfcHVibGljX2tleTogJ2h0dHBzOi8vcHJvLXVrLWFwaXMuc3ZjLmF6dWstc2NjLXByb2QuZXczLmF3cy5henRlYy5jbG91ZC5hbGxpYW56L2VkZ2VtaWNyby1hdXRoL3B1YmxpY0tleScKICBtYW5hZ2VtZW50VXJpOiAnaHR0cHM6Ly9lZGdlLWFwaXMuc3ZjLmF6dWstc2NjLXByb2QuZXczLmF3cy5henRlYy5jbG91ZC5hbGxpYW56JwogIHZhdWx0TmFtZTogbWljcm9nYXRld2F5CiAgYXV0aFVyaTogJ2h0dHBzOi8vcHJvLXVrLWFwaXMuc3ZjLmF6dWstc2NjLXByb2QuZXczLmF3cy5henRlYy5jbG91ZC5hbGxpYW56L2VkZ2VtaWNyby1hdXRoJwogIGJhc2VVcmk6ICdodHRwczovL3Byby11ay1hcGlzLnN2Yy5henVrLXNjYy1wcm9kLmV3My5hd3MuYXp0ZWMuY2xvdWQuYWxsaWFuei9lZGdlbWljcm8vJXMvb3JnYW5pemF0aW9uLyVzL2Vudmlyb25tZW50LyVzJwogIGJvb3RzdHJhcE1lc3NhZ2U6IFBsZWFzZSBjb3B5IHRoZSBmb2xsb3dpbmcgcHJvcGVydHkgdG8gdGhlIGVkZ2UgbWljcm8gYWdlbnQgY29uZmlnCiAga2V5U2VjcmV0TWVzc2FnZTogVGhlIGZvbGxvd2luZyBjcmVkZW50aWFscyBhcmUgcmVxdWlyZWQgdG8gc3RhcnQgZWRnZSBtaWNybwogIHByb2R1Y3RzOiAnaHR0cHM6Ly9wcm8tdWstYXBpcy5zdmMuYXp1ay1zY2MtcHJvZC5ldzMuYXdzLmF6dGVjLmNsb3VkLmFsbGlhbnovZWRnZW1pY3JvLWF1dGgvcHJvZHVjdHMnCmVkZ2VtaWNybzoKICBwb3J0OiA4MDAwCiAgcHJveHk6CiAgICB0dW5uZWw6IGZhbHNlCiAgICB1cmw6CiAgICBlbmFibGVkOiBmYWxzZQogIG1heF9jb25uZWN0aW9uczogMTAwMAogICNjb25maWdfY2hhbmdlX3BvbGxfaW50ZXJ2YWw6IDM2MDAKICBkaXNhYmxlX2NvbmZpZ19wb2xsX2ludGVydmFsOiB0cnVlCiAgbG9nZ2luZzoKICAgIGxldmVsOiBpbmZvCiAgICBkaXI6IC92YXIvdG1wCiAgICBzdGF0c19sb2dfaW50ZXJ2YWw6IDYwCiAgICByb3RhdGVfaW50ZXJ2YWw6IDI0CiAgcGx1Z2luczoKICAgIHNlcXVlbmNlOgogICAgICAtIGhlYWx0aGNoZWNrCiAgICAgIC0gc2VydmljZWNoZWNrCiAgICAgIC0gb2F1dGgKICAgICAgLSBzY29wZXNjaGVjawoKaGVhZGVyczoKICB4LWZvcndhcmRlZC1mb3I6IHRydWUKICB4LWZvcndhcmRlZC1ob3N0OiB0cnVlCiAgeC1yZXF1ZXN0LWlkOiB0cnVlCiAgeC1yZXNwb25zZS10aW1lOiB0cnVlCiAgdmlhOiB0cnVlCmhlYWx0aGNoZWNrOgogIGhlYWx0aGNoZWNrX3VybDogL2hlYWx0aApzZXJ2aWNlY2hlY2s6CiAgc2VydmljZWNoZWNrX3VybDogL19faGVhbHRoCiAgc2VydmljZWNoZWNrX3BvcnQ6IDgwODAKb2F1dGg6CiAgYWxsb3dOb0F1dGhvcml6YXRpb246IGZhbHNlCiAgYWxsb3dJbnZhbGlkQXV0aG9yaXphdGlvbjogZmFsc2UKICBhbGxvd09BdXRoT25seTogdHJ1ZQogIGFsbG93QVBJS2V5T25seTogZmFsc2UKICBrZWVwLWF1dGhvcml6YXRpb24taGVhZGVyOiB0cnVlCiAgZ3JhY2VQZXJpb2Q6IDEwCiAgdmVyaWZ5X2FwaV9rZXlfdXJsOiAnaHR0cHM6Ly9wcm8tdWstYXBpcy5zdmMuYXp1ay1zY2MtcHJvZC5ldzMuYXdzLmF6dGVjLmNsb3VkLmFsbGlhbnovZWRnZW1pY3JvLWF1dGgvdmVyaWZ5QXBpS2V5JwogIGNhY2hlS2V5OiB0cnVlCnNjb3Blc2NoZWNrOgogIHNjb3Blc2NoZWNrX2xpc3Q6ICJQT1NUPXVybjphenVrOnBlcnNvbmFsOmFuaW1hbGhlYWx0aDpzYTpsdjpjbG91ZDpldmVudC1wcm9qZWN0b3IiCmFuYWx5dGljczoKICB1cmk6ID4tCiAgICBodHRwczovL3Byby11ay1hcGlzLnN2Yy5henVrLXNjYy1wcm9kLmV3My5hd3MuYXp0ZWMuY2xvdWQuYWxsaWFuei9lZGdlbWljcm8vYXhwdWJsaXNoZXIvb3JnYW5pemF0aW9uL3VrL2Vudmlyb25tZW50L2ludGVybmFsCiAgYnVmZmVyU2l6ZTogMTAwMDAKICBiYXRjaFNpemU6IDIwMDAKICBmbHVzaEludGVydmFsOiAzNjAwMDAwCiAgcmVsYXRpdmVQYXRoOiAvX19oZWFsdGg=
    - name: EDGEMICRO_ORG
      value: uk
    - name: EDGEMICRO_ENV
      value: internal
    - name: EDGEMICRO_KEY
      valueFrom:
        secretKeyRef:
          name: apigee-secret
          key: EDGEMICRO_KEY_INTERNAL
    - name: EDGEMICRO_SECRET
      valueFrom:
        secretKeyRef:
          name: apigee-secret
          key: EDGEMICRO_SECRET_INTERNAL
    - name: EDGEMICRO_PROCESSES
      value: "2"
    - name: SERVICE_NAME
      value: ah-sa-lv-event-projector
    - name: PROXY_NAME
      value: edgemicro_ah-sa-lv-event-projector
    - name: CONTAINER_PORT
      value: "8080"
    - name: EDGEMICRO_BASE_PATH
      value: /
    - name: EDGEMICRO_LOCAL_PROXY
      value: "1"
    - name: NODE_EXTRA_CA_CERTS
      value: /opt/apigee/certs/ca-certificates.crt
    - name: EDGEMICRO_PLUGIN_DIR
      value: /usr/local/lib/node_modules/edgemicro/plugins/


#Add a readiness gate with conditionType:
#target-health.alb.ingress.k8s.aws/<ingress name>_<service name>_<service port> to your pod.
#This is required if the target type in ALB ingress is ip
readinessGates:
  enabled: true
  conditions:
    - conditionType: target-health.alb.ingress.k8s.aws/ah-sa_azukp-ah-sa-lv-event-projector-emg_8000

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 150
  targetMemoryUtilizationPercentage: 150